In [17]:
import pandas as pd
data=pd.read_csv('CIBERSORTx_GSE76772_clean.csv')
samples=data['Mixture'].values
samples

array(['sample1', 'sample3', 'sample5', 'sample7', 'sample9', 'sample11',
       'sample13', 'sample15', 'sample17', 'sample19', 'sample21',
       'sample23'], dtype=object)

In [18]:
data.set_index('Mixture',inplace=True)
data

,B cells naive,B cells memory,Plasma cells,T cells CD8,T cells CD4 naive,T cells CD4 memory resting,T cells CD4 memory activated,T cells follicular helper,T cells regulatory (Tregs),T cells gamma delta,...,Macrophages M2,Dendritic cells resting,Dendritic cells activated,Mast cells resting,Mast cells activated,Eosinophils,Neutrophils,P-value,Correlation,RMSE
Mixture,,,,,,,,,,,,,,,,,,,,,
sample1,0.098624,0.000000,0.038984,0.000000,0.000000,0.216883,0.000000,0.003292,0.002204,0,...,0.134865,0.238090,0.009109,0.005226,0.000000,0.000684,0,0.002,0.332790,0.944283
sample3,0.059168,0.000000,0.079964,0.052406,0.000000,0.086717,0.012296,0.000000,0.000000,0,...,0.287153,0.157159,0.000000,0.072740,0.000000,0.018081,0,0.000,0.444763,0.898635
sample5,0.018674,0.000000,0.033487,0.000000,0.000000,0.182453,0.000000,0.000000,0.004914,0,...,0.351573,0.126989,0.000000,0.024474,0.000000,0.026837,0,0.000,0.378268,0.925814
sample7,0.000000,0.059581,0.078345,0.040488,0.072378,0.037478,0.001339,0.000000,0.000000,0,...,0.302836,0.206538,0.005725,0.098683,0.000000,0.000000,0,0.000,0.423870,0.907298
sample9,0.158748,0.000000,0.017252,0.000000,0.071639,0.108949,0.000000,0.000000,0.000000,0,...,0.156039,0.150324,0.000000,0.020283,0.000000,0.000000,0,0.008,0.246708,0.979598
sample11,0.000000,0.101620,0.095012,0.000000,0.000000,0.000000,0.010545,0.003106,0.000000,0,...,0.007251,0.230614,0.000000,0.027465,0.000000,0.016220,0,0.002,0.322780,0.952039
sample13,0.087624,0.000000,0.025005,0.011431,0.000000,0.121707,0.000000,0.007712,0.000000,0,...,0.077754,0.249411,0.000000,0.001837,0.005238,0.000000,0,0.000,0.406810,0.913975
sample15,0.000000,0.154482,0.114390,0.068490,0.008650,0.066317,0.000000,0.000000,0.000000,0,...,0.148137,0.141778,0.000000,0.021446,0.000000,0.033701,0,0.000,0.449896,0.893921
sample17,0.082274,0.000000,0.066145,0.000000,0.000000,0.114993,0.000253,0.000000,0.002547,0,...,0.148650,0.192811,0.008094,0.075483,0.000000,0.032210,0,0.006,0.262497,0.970375
sample19,0.000000,0.037077,0.036458,0.000000,0.009927,0.114797,0.013001,0.000000,0.000000,0,...,0.289593,0.206695,0.000000,0.092543,0.000000,0.019744,0,0.000,0.430556,0.904737
sample21,0.090293,0.000000,0.083942,0.000000,0.000000,0.245619,0.000000,0.000000,0.000000,0,...,0.107669,0.211736,0.000000,0.044457,0.000000,0.020772,0,0.002,0.341810,0.940208
sample23,0.000000,0.018557,0.082654,0.000000,0.002537,0.114399,0.022370,0.000000,0.000000,0,...,0.119765,0.218385,0.000000,0.063047,0.000000,0.028234,0,0.002,0.338308,0.941867

In [19]:
genes=pd.read_csv('HUGO_GSE76772.csv')
genes.set_index('Gene_Symbol',inplace=True)
genes=genes[samples]
genes=genes.T
genes.head()

Gene_Symbol,GNAI3,PBSN,CDC45,H19,SCML2,APOH,NARF,CAV2,KLF6,SCMH1,...,GM22395,VMN1R-PS47,GM22396,NaN,GM22394,NaN,NaN,NaN,VMN1R-PS147,METHIG1
sample1,1779,0,204,510,75,0,919,702,1191,289,...,0,0,0,0,0,0,0,0,0,0
sample3,1647,0,203,89,5,0,784,597,1228,342,...,0,0,0,0,0,0,0,0,0,0
sample5,1678,0,174,274,47,0,922,436,876,235,...,0,0,0,0,0,0,0,0,0,0
sample7,1792,0,168,200,0,0,703,437,1018,178,...,0,0,0,0,0,0,0,0,0,0
sample9,1770,0,221,350,31,0,732,749,1277,178,...,0,0,0,0,0,0,0,0,0,0

In [20]:
data['IL12']=genes['IL12A']+genes['IL12B']
data['HMGB1']=genes['HMGB1']
data['IL6']=genes['IL6']+genes['IL6ST']+genes['IL6RA']
data['IL10']=genes['IL10']+genes['IL10RB']+genes['IL10RA']
data['IFNG']=genes['IFNG']
data.head()

,B cells naive,B cells memory,Plasma cells,T cells CD8,T cells CD4 naive,T cells CD4 memory resting,T cells CD4 memory activated,T cells follicular helper,T cells regulatory (Tregs),T cells gamma delta,...,Eosinophils,Neutrophils,P-value,Correlation,RMSE,IL12,HMGB1,IL6,IL10,IFNG
Mixture,,,,,,,,,,,,,,,,,,,,,
sample1,0.098624,0.000000,0.038984,0.000000,0.000000,0.216883,0.000000,0.003292,0.002204,0,...,0.000684,0,0.002,0.332790,0.944283,28,1000,2490,417,0
sample3,0.059168,0.000000,0.079964,0.052406,0.000000,0.086717,0.012296,0.000000,0.000000,0,...,0.018081,0,0.000,0.444763,0.898635,24,940,1766,351,0
sample5,0.018674,0.000000,0.033487,0.000000,0.000000,0.182453,0.000000,0.000000,0.004914,0,...,0.026837,0,0.000,0.378268,0.925814,0,1103,1599,404,0
sample7,0.000000,0.059581,0.078345,0.040488,0.072378,0.037478,0.001339,0.000000,0.000000,0,...,0.000000,0,0.000,0.423870,0.907298,2,1050,1880,455,0
sample9,0.158748,0.000000,0.017252,0.000000,0.071639,0.108949,0.000000,0.000000,0.000000,0,...,0.000000,0,0.008,0.246708,0.979598,0,1182,1602,450,0

In [21]:
SS_variable_list=['Tn', 'Th', 'Tc', 'Tr', 'Dn', 'D', 'Mn', 'M', 'C', 'N', 'A','Ig','H','IL12','IL10','IL6']
IC_variable_list=['Tn', 'Th', 'Tc', 'Tr', 'Dn', 'D', 'Mn', 'M', 'C', 'N', 'A','Ig','H','IL12','IL10','IL6']
Immune_cells=['Tn', 'Th', 'Tc', 'Tr', 'Dn', 'D', 'Mn', 'M']
model_cells=['Tn', 'Th', 'Tc', 'Tr', 'Dn', 'D', 'M','Mn']

In [22]:
index=data.index
# rearrange the data corresponding to variables
full_data=pd.DataFrame(index=index)
full_data['Sample ID']=data.index
full_data['Tn']=data[['T cells CD4 naive', 'T cells CD4 memory resting', 'NK cells resting']].sum(axis=1)
full_data['Th']=data['T cells CD4 memory activated']+data['T cells follicular helper']
full_data['Tc']=data['T cells CD8']+data['NK cells activated']
full_data['Tr']=data['T cells regulatory (Tregs)']
full_data['Dn']=data['Dendritic cells resting']
full_data['D']=data['Dendritic cells activated']
full_data['M']=data['Macrophages M1']+data['Macrophages M2']
full_data['Mn']=data[['Monocytes', 'Macrophages M0']].sum(axis=1)
full_data['C']=""
full_data['N']=""
full_data['IL12']=data['IL12']
full_data['IL10']=data['IL10']
full_data['IL6']=data['IL6']
full_data['H']=data['HMGB1']
full_data['Ig']=data['IFNG']
#full_data['Tumor_weight']=data['Tumor_weight']
#full_data['dim']=data['Tumor_Size']

full_data['TIC']=full_data[['Tn', 'Th', 'Tc', 'Tr','Dn', 'D', 'M','Mn']].sum(axis=1)

#Substitute zeros with something negligibly small, but positive
mincellvalue=full_data[Immune_cells].to_numpy()[:]
mincellvalue=mincellvalue[mincellvalue>0].min()
for key in Immune_cells:
    full_data.loc[full_data[key]<=0, key]=0.1*mincellvalue

In [23]:
full_data

,Sample ID,Tn,Th,Tc,Tr,Dn,D,M,Mn,C,N,IL12,IL10,IL6,H,Ig,TIC
Mixture,,,,,,,,,,,,,,,,,
sample1,sample1,0.345360,0.003292,0.000025,0.002204,0.238090,0.009109,0.134865,0.123562,,,28,417,2490,1000,0,0.856482
sample3,sample3,0.123642,0.012296,0.078135,0.000025,0.157159,0.000025,0.287153,0.111662,,,24,351,1766,940,0,0.770046
sample5,sample5,0.292502,0.000025,0.003004,0.004914,0.126989,0.000025,0.358593,0.110526,,,0,404,1599,1103,0,0.896528
sample7,sample7,0.160805,0.001339,0.040488,0.000025,0.206538,0.005725,0.314847,0.033648,,,2,455,1880,1050,0,0.763391
sample9,sample9,0.245880,0.000025,0.000025,0.000025,0.150324,0.000025,0.156039,0.251475,,,0,450,1602,1182,0,0.803717
sample11,sample11,0.044031,0.013651,0.000025,0.000025,0.230614,0.000025,0.010966,0.460421,,,16,723,1068,932,0,0.759683
sample13,sample13,0.121707,0.007712,0.048066,0.000025,0.249411,0.000025,0.079407,0.373993,,,0,429,1646,945,0,0.880296
sample15,sample15,0.191579,0.000025,0.068490,0.000025,0.141778,0.000025,0.150254,0.123881,,,0,319,1490,807,0,0.675981
sample17,sample17,0.188318,0.000253,0.041649,0.002547,0.192811,0.008094,0.148650,0.161566,,,19,511,3327,1521,0,0.743887
sample19,sample19,0.194266,0.013001,0.004083,0.000025,0.206695,0.000025,0.290524,0.105609,,,3,566,3481,1549,0,0.814178
sample21,sample21,0.307923,0.000025,0.010574,0.000025,0.211736,0.000025,0.111992,0.118310,,,0,349,1716,957,0,0.760536
sample23,sample23,0.189278,0.022370,0.009591,0.000025,0.218385,0.000025,0.125346,0.242538,,,4,278,1490,779,0,0.807507

In [24]:
full_data['tumor_size']=[1,4,7,10,1,4,7,10,1,4,7,10]
full_data['samples']=[1,1,1,1,2,2,2,2,3,3,3,3]

In [25]:
import numpy as np

meandim=np.empty(3)
#meandim[0]=full_data_meta['dim'].mean()
for i in range(3):
    meandim[i]=full_data[full_data['samples']==i+1]['tumor_size'].mean()


meandim

array([5.5, 5.5, 5.5])

In [26]:
# Mean total immune cell count global and for each cluster
meanTIC=np.empty(3)

for i in range(3):
    meanTIC[i]=full_data[full_data['samples']==i+1]['TIC'].mean()
meanTIC

array([0.82161182, 0.77991955, 0.78152701])

In [27]:
s1=full_data[full_data.samples==1]
s2=full_data[full_data.samples==2]
s3=full_data[full_data.samples==3]

In [28]:
#total cell number TCN 
#collaborators suggested C:I:N ratio 0.955:0.04:0.005
# Evaluating number of cancer and necrotic cells from tumor size and immune cells
#We subtract the total number of immune cells from total number of cells to get the total number of cancer+necrosis. Then based on 0.955:0.005 ratio when multiplied by 955/960 we only get cancers.
#Necrotic cells are 1/191 of cancer cells according to 0.955:0.005 ratio
#literature says 4.5e1 is the density of epithelial cells. So by this multiplication we will make sure the average density of immune cells matches this number
#literature says 4.5e1 is the density of epithelial cells. So by this multiplication we will make sure the average density of cancer cells and necrotic cells matches this number. The reason we use 0.955 for both is because before this multiplication the ratio 0.955:0.005 holds between C and N. So we devide by 0.955 for both to keep the ratio.

s1.C=955*((s1.tumor_size/meandim[0])-0.04*(s1.TIC/meanTIC[0]))/960 
s1.N=s1.C/191               
s1[Immune_cells]*=4.5e1/meanTIC[0]      
s1[['C', 'N']]*=4.5e1/0.955        
s1['A']=s1[['Tn', 'Th', 'Tc', 'Tr', 'Dn', 'D', 'Mn', 'M']].sum(axis=1)*2
s1

C:\Users\na_mi\AppData\Roaming\Python\Python37\site-packages\pandas\core\generic.py:5170: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[name] = value
C:\Users\na_mi\AppData\Roaming\Python\Python37\site-packages\pandas\core\frame.py:3069: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]
c:\users\na_mi\appdata\local\programs\python\python37-32\lib\site-packages\ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  del sys.path[0]

,Sample ID,Tn,Th,Tc,Tr,Dn,D,M,Mn,C,N,IL12,IL10,IL6,H,Ig,TIC,tumor_size,samples,A
Mixture,,,,,,,,,,,,,,,,,,,,
sample1,sample1,18.915518,0.180307,0.001385,0.120725,13.040278,0.498882,7.386616,6.767523,6.568150,0.034388,28,417,2490,1000,0,0.856482,1,1,93.822468
sample3,sample3,6.771898,0.673464,4.279462,0.001385,8.607666,0.001385,15.727466,6.115784,32.333587,0.169286,24,351,1766,940,0,0.770046,4,1,84.357020
sample5,sample5,16.020474,0.001385,0.164525,0.269144,6.955235,0.001385,19.640266,6.053538,57.613125,0.301639,0,404,1599,1103,0,0.896528,7,1,98.211905
sample7,sample7,8.807364,0.073352,2.217549,0.001385,11.312168,0.313571,17.244315,1.842909,83.485138,0.437095,2,455,1880,1050,0,0.763391,10,1,83.625226

In [29]:
## Correcting negative cancer and necrotic cell counts (No need)

#minC=s1.loc[s1.C>0, 'C'].min()
#s1.loc[s1.C<=0, 'C']=0.1*minC
#s1.loc[s1.N<0, 'N']=0
#s1

In [30]:
#total cell number TCN 
#collaborators suggested C:I:N ratio 0.955:0.04:0.005
# Evaluating number of cancer and necrotic cells from tumor size and immune cells
#We subtract the total number of immune cells from total number of cells to get the total number of cancer+necrosis. Then based on 0.955:0.005 ratio when multiplied by 955/960 we only get cancers.
#Necrotic cells are 1/191 of cancer cells according to 0.955:0.005 ratio
#literature says 4.5e1 is the density of epithelial cells. So by this multiplication we will make sure the average density of immune cells matches this number
#literature says 4.5e1 is the density of epithelial cells. So by this multiplication we will make sure the average density of cancer cells and necrotic cells matches this number. The reason we use 0.955 for both is because before this multiplication the ratio 0.955:0.005 holds between C and N. So we devide by 0.955 for both to keep the ratio.

s2.C=955*((s2.tumor_size/meandim[1])-0.04*(s2.TIC/meanTIC[1]))/960 
s2.N=s2.C/191               
s2[Immune_cells]*=4.5e1/meanTIC[1]      
s2[['C', 'N']]*=4.5e1/0.955        
s2['A']=s2[['Tn', 'Th', 'Tc', 'Tr', 'Dn', 'D', 'Mn', 'M']].sum(axis=1)*2
s2

C:\Users\na_mi\AppData\Roaming\Python\Python37\site-packages\pandas\core\generic.py:5170: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[name] = value
C:\Users\na_mi\AppData\Roaming\Python\Python37\site-packages\pandas\core\frame.py:3069: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]
c:\users\na_mi\appdata\local\programs\python\python37-32\lib\site-packages\ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  del sys.path[0]

,Sample ID,Tn,Th,Tc,Tr,Dn,D,M,Mn,C,N,IL12,IL10,IL6,H,Ig,TIC,tumor_size,samples,A
Mixture,,,,,,,,,,,,,,,,,,,,
sample9,sample9,14.186820,0.001459,0.001459,0.001459,8.673440,0.001459,9.003160,14.509677,6.590515,0.034505,0,450,1602,1182,0,0.803717,1,2,92.757866
sample11,sample11,2.540510,0.787626,0.001459,0.001459,13.306040,0.001459,0.632713,26.565508,32.264559,0.168924,16,723,1068,932,0,0.759683,4,2,87.673548
sample13,sample13,7.022259,0.444987,2.773333,0.001459,14.390571,0.001459,4.581648,21.578756,57.542776,0.301271,0,429,1646,945,0,0.880296,7,2,101.588943
sample15,sample15,11.053770,0.001459,3.951772,0.001459,8.180317,0.001459,8.669383,7.147710,83.602150,0.437708,0,319,1490,807,0,0.675981,10,2,78.014657

In [31]:
## Correcting negative cancer and necrotic cell counts (no need)

#minC=s2.loc[s2.C>0, 'C'].min()
#s2.loc[s2.C<=0, 'C']=0.1*minC
#s2.loc[s2.N<0, 'N']=0
#s2

In [32]:
#total cell number TCN 
#collaborators suggested C:I:N ratio 0.955:0.04:0.005
# Evaluating number of cancer and necrotic cells from tumor size and immune cells
#We subtract the total number of immune cells from total number of cells to get the total number of cancer+necrosis. Then based on 0.955:0.005 ratio when multiplied by 955/960 we only get cancers.
#Necrotic cells are 1/191 of cancer cells according to 0.955:0.005 ratio
#literature says 4.5e1 is the density of epithelial cells. So by this multiplication we will make sure the average density of immune cells matches this number
#literature says 4.5e1 is the density of epithelial cells. So by this multiplication we will make sure the average density of cancer cells and necrotic cells matches this number. The reason we use 0.955 for both is because before this multiplication the ratio 0.955:0.005 holds between C and N. So we devide by 0.955 for both to keep the ratio.


s3.C=955*((s3.tumor_size/meandim[2])-0.04*(s3.TIC/meanTIC[2]))/960 
s3.N=s3.C/191               
s3[Immune_cells]*=4.5e1/meanTIC[2]      
s3[['C', 'N']]*=4.5e1/0.955        
s3['A']=s3[['Tn', 'Th', 'Tc', 'Tr', 'Dn', 'D', 'Mn', 'M']].sum(axis=1)*2
s3

C:\Users\na_mi\AppData\Roaming\Python\Python37\site-packages\pandas\core\generic.py:5170: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[name] = value
C:\Users\na_mi\AppData\Roaming\Python\Python37\site-packages\pandas\core\frame.py:3069: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]
c:\users\na_mi\appdata\local\programs\python\python37-32\lib\site-packages\ipykernel_launcher.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,Sample ID,Tn,Th,Tc,Tr,Dn,D,M,Mn,C,N,IL12,IL10,IL6,H,Ig,TIC,tumor_size,samples,A
Mixture,,,,,,,,,,,,,,,,,,,,
sample17,sample17,10.843278,0.014559,2.398143,0.146630,11.101956,0.466044,8.559201,9.302918,6.738030,0.035278,19,511,3327,1521,0,0.743887,1,3,85.665461
sample19,sample19,11.185749,0.748596,0.235111,0.001456,11.901393,0.001456,16.728225,6.080938,32.137575,0.168260,3,566,3481,1549,0,0.814178,4,3,93.765849
sample21,sample21,17.730088,0.001456,0.608837,0.001456,12.191684,0.001456,6.448463,6.812254,57.834452,0.302798,0,349,1716,957,0,0.760536,7,3,87.591387
sample23,sample23,10.898531,1.288033,0.552229,0.001456,12.574527,0.001456,7.217389,13.965222,83.289942,0.436073,4,278,1490,779,0,0.807507,10,3,92.997686

In [33]:
## Correcting negative cancer and necrotic cell counts (no need)

#minC=s3.loc[s3.C>0, 'C'].min()
#s3.loc[s3.C<=0, 'C']=0.1*minC
#s3.loc[s3.N<0, 'N']=0
#s3

In [34]:
s1[0:1]

,Sample ID,Tn,Th,Tc,Tr,Dn,D,M,Mn,C,N,IL12,IL10,IL6,H,Ig,TIC,tumor_size,samples,A
Mixture,,,,,,,,,,,,,,,,,,,,
sample1,sample1,18.915518,0.180307,0.001385,0.120725,13.040278,0.498882,7.386616,6.767523,6.56815,0.034388,28,417,2490,1000,0,0.856482,1,1,93.822468

In [35]:
#time course data for each mouse
Mouse1=pd.concat([s1[0:4]])
Mouse1.to_csv('Mouse1.csv')
Mouse2=pd.concat([s2[0:4]])
Mouse2.to_csv('Mouse2.csv')
Mouse3=pd.concat([s3[0:4]])
Mouse3.to_csv('Mouse3.csv')

# S1, S2 and S3 are each sample model variable values in four different time points( 6w,8w, 10w, 12w)

In [19]:
#initial data for each sample  (W6 values of each sample)
IC_data=pd.concat([s1[0:1],s2[0:1],s3[0:1]])
IC_data.to_csv('IC_data.csv')
IC_data

,Sample ID,Tn,Th,Tc,Tr,Dn,D,M,Mn,C,N,IL12,IL10,IL6,H,Ig,TIC,tumor_size,samples,A
Mixture,,,,,,,,,,,,,,,,,,,,
sample1,sample1,18.915518,0.180307,0.001385,0.120725,13.040278,0.498882,7.386616,6.767523,6.568150,0.034388,28,0,17,1000,0,0.856482,1,1,93.822468
sample9,sample9,14.186820,0.001459,0.001459,0.001459,8.673440,0.001459,9.003160,14.509677,6.590515,0.034505,0,0,0,1182,0,0.803717,1,2,92.757866
sample17,sample17,10.843278,0.014559,2.398143,0.146630,11.101956,0.466044,8.559201,9.302918,6.738030,0.035278,19,0,0,1521,0,0.743887,1,3,85.665461

In [20]:
#large data for each sample (w12 values of each sample)
large_data=pd.concat([s1[3:4],s2[3:4],s3[3:4]])
large_data.to_csv('Steady_state.csv')
large_data

,Sample ID,Tn,Th,Tc,Tr,Dn,D,M,Mn,C,N,IL12,IL10,IL6,H,Ig,TIC,tumor_size,samples,A
Mixture,,,,,,,,,,,,,,,,,,,,
sample7,sample7,8.807364,0.073352,2.217549,0.001385,11.312168,0.313571,17.244315,1.842909,83.485138,0.437095,2,0,0,1050,0,0.763391,10,1,83.625226
sample15,sample15,11.053770,0.001459,3.951772,0.001459,8.180317,0.001459,8.669383,7.147710,83.602150,0.437708,0,3,2,807,0,0.675981,10,2,78.014657
sample23,sample23,10.898531,1.288033,0.552229,0.001456,12.574527,0.001456,7.217389,13.965222,83.289942,0.436073,4,0,1,779,0,0.807507,10,3,92.997686

In [21]:
max_values=pd.concat([s1.max(),s2.max(),s3.max()],axis=1)
max_values=max_values.T
max_values

,Sample ID,Tn,Th,Tc,Tr,Dn,D,M,Mn,C,N,IL12,IL10,IL6,H,Ig,TIC,tumor_size,samples,A
0,sample7,18.9155,0.673464,4.27946,0.269144,13.0403,0.498882,19.6403,6.76752,83.4851,0.437095,28,0,17,1103,0,0.896528,10,1,98.2119
1,sample9,14.1868,0.787626,3.95177,0.00145893,14.3906,0.00145893,9.00316,26.5655,83.6021,0.437708,16,3,2,1182,0,0.880296,10,2,101.589
2,sample23,17.7301,1.28803,2.39814,0.14663,12.5745,0.466044,16.7282,13.9652,83.2899,0.436073,19,0,6,1549,0,0.814178,10,3,93.7658

In [22]:
a=max_values.max()
a.to_csv('max_values.csv')

In [23]:
a

Sample ID      sample9
Tn             18.9155
Th             1.28803
Tc             4.27946
Tr            0.269144
Dn             14.3906
D             0.498882
M              19.6403
Mn             26.5655
C              83.6021
N             0.437708
IL12                28
IL10                 3
IL6                 17
H                 1549
Ig                   0
TIC           0.896528
tumor_size          10
samples              3
A              101.589
dtype: object

In [24]:
s1.max()

Sample ID      sample7
Tn             18.9155
Th            0.673464
Tc             4.27946
Tr            0.269144
Dn             13.0403
D             0.498882
M              19.6403
Mn             6.76752
C              83.4851
N             0.437095
IL12                28
IL10                 0
IL6                 17
H                 1103
Ig                   0
TIC           0.896528
tumor_size          10
samples              1
A              98.2119
dtype: object

In [25]:
mean_Values=pd.concat([s1.mean(),s2.mean(),s3.mean()],axis=1)
mean_Values=mean_Values.T
mean_Values

,Tn,Th,Tc,Tr,Dn,D,M,Mn,C,N,IL12,IL10,IL6,H,Ig,TIC,tumor_size,samples,A
0,12.628814,0.232127,1.665730,0.098160,9.978837,0.203806,14.999666,5.194938,45.0,0.235602,13.5,0.00,4.25,1023.25,0.0,0.821612,5.5,1.0,90.004155
1,8.700839,0.308883,1.682006,0.001459,11.137592,0.001459,5.721726,17.450413,45.0,0.235602,4.0,0.75,0.50,966.50,0.0,0.779920,5.5,2.0,90.008754
2,12.664412,0.513161,0.948580,0.037749,11.942390,0.117603,9.738320,9.040333,45.0,0.235602,6.5,0.00,1.75,1201.50,0.0,0.781527,5.5,3.0,90.005096

In [26]:
b=mean_Values.mean()
b.to_csv('mean_values.csv')
b

Tn              11.331355
Th               0.351390
Tc               1.432105
Tr               0.045789
Dn              11.019606
D                0.107623
M               10.153237
Mn              10.561895
C               45.000000
N                0.235602
IL12             8.000000
IL10             0.250000
IL6              2.166667
H             1063.750000
Ig               0.000000
TIC              0.794353
tumor_size       5.500000
samples          2.000000
A               90.006001
dtype: float64